engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 40

ratings:
  paths:
    - models/**/*
    - database/**/*
    - api/**/*
    - app.js
    - package.json

exclude_paths:
  - test/**/*