'use strict';

const MIN_VELOCITY = 10;
const MAX_VELOCITY = 25;
const ACCELERATION = 0.5;
const CHARACTER_SIZE = 50;
const FIRE_RATE = 150;
const MAX_AMMO = 50;
const SERVER_PORT = '8181';
const STAGE_WIDTH = 1300;
const STAGE_HEIGHT = 844;
const SHIELD_MAX_DAMAGE = 10;
const ROTATE_LEFT = -2;
const ROTATE_RIGHT = +2;

module.exports = {
  MIN_VELOCITY,
  MAX_VELOCITY,
  ACCELERATION,
  CHARACTER_SIZE,
  FIRE_RATE,
  MAX_AMMO,
  SERVER_PORT,
  STAGE_WIDTH,
  STAGE_HEIGHT,
  SHIELD_MAX_DAMAGE,
  ROTATE_LEFT,
  ROTATE_RIGHT
};
